/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    categories: Category;
    services: Service;
    testimonials: Testimonial;
    posts: Post;
    faqs: Faq;
    media: Media;
    'form-submissions': FormSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
    navigation: Navigation;
    announcement: Announcement;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    announcement: AnnouncementSelect<false> | AnnouncementSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Case studies shown in the work grid and the featured build block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Leave empty to generate from "title".
   */
  slug: string;
  category: number | Category;
  year: string;
  description: string;
  /**
   * Main visual for the project card. Without this the card renders empty.
   */
  image?: (number | null) | Media;
  /**
   * Alt text for the card image. Falls back to the media alt text.
   */
  imageAlt?: string | null;
  /**
   * Case study images, rendered in order on the detail page.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Short result chips, e.g. "+42% sign-ups".
   */
  metrics?: string[] | null;
  /**
   * Stored for the future project detail page.
   */
  deliverables?: string[] | null;
  /**
   * Stored for the future project detail page.
   */
  quote?: string | null;
  size?: ('standard' | 'wide' | 'tall') | null;
  /**
   * Highlighted in the featured build block.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Project categories. Each one gets a page at /work/<slug>, using the layout picked on the Page tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Leave empty to generate from "name".
   */
  slug: string;
  /**
   * Unique identifier, e.g. custom-commerce.
   */
  key: string;
  /**
   * Which filter tab this category belongs to. Must match a key in Home page > Work > Filters.
   */
  filter: string;
  order?: number | null;
  page: {
    /**
     * How the projects on this category page are presented.
     */
    layout: 'grid' | 'showcase' | 'editorial';
    /**
     * Small label above the heading, e.g. "Category".
     */
    eyebrow?: string | null;
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    heading?: string | null;
    intro?: string | null;
    /**
     * Optional. Used as a full-width band by the showcase layout.
     */
    heroImage?: (number | null) | Media;
    seo?: {
      /**
       * Falls back to "Category name — site title" when empty.
       */
      title?: string | null;
      /**
       * Falls back to the intro above when empty.
       */
      description?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploads used across the site: project imagery, hero carousel, OG image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Offer cards in the services section and the footer services column.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Display index, e.g. "01".
   */
  number: string;
  title: string;
  description: string;
  /**
   * Bullet chips listed under the description.
   */
  items?: string[] | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client reviews shown in the reviews section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Notes and process write-ups. Not linked from the site yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Leave empty to generate from "title".
   */
  slug: string;
  /**
   * Label shown above the title, e.g. "Process / 01".
   */
  kind: string;
  visual: 'orbit' | 'type' | 'colour' | 'shape' | 'desk' | 'grid';
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form requests sent from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  /**
   * Which enquiry button the visitor picked.
   */
  topic?: string | null;
  message: string;
  /**
   * Page the submission came from.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name used inside the admin panel.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  year?: T;
  description?: T;
  image?: T;
  imageAlt?: T;
  gallery?: T;
  metrics?: T;
  deliverables?: T;
  quote?: T;
  size?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  key?: T;
  filter?: T;
  order?: T;
  page?:
    | T
    | {
        layout?: T;
        eyebrow?: T;
        heading?: T;
        intro?: T;
        heroImage?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  description?: T;
  items?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  visual?: T;
  excerpt?: T;
  content?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  topic?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every block of copy on the single page site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    badge?: string | null;
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    heading: string;
    skills?: string[] | null;
    description?: string | null;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * e.g. "Monfolio Studio — Jakarta + remote".
     */
    locationBadge?: string | null;
    availability?: string | null;
    /**
     * Muted suffix, e.g. "2 project slots".
     */
    availabilityNote?: string | null;
    carousel?:
      | {
          image: number | Media;
          /**
           * e.g. "Mora Coffee — Brand".
           */
          caption: string;
          id?: string | null;
        }[]
      | null;
    marquee?: string[] | null;
  };
  about?: {
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    heading?: string | null;
    intro?: string | null;
    tiles?:
      | {
          label: string;
          caption: string;
          variant: 'accent' | 'dark';
          id?: string | null;
        }[]
      | null;
    pillars?:
      | {
          label: string;
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  work: {
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    heading?: string | null;
    intro?: string | null;
    /**
     * Tabs above the project grid. Each category is assigned to one of these keys.
     */
    filters?:
      | {
          label: string;
          /**
           * Use "all" for the unfiltered tab.
           */
          key: string;
          id?: string | null;
        }[]
      | null;
    /**
     * How many project cards show before "show all".
     */
    maxVisible?: number | null;
    showAllLabel?: string | null;
    showLessLabel?: string | null;
    featured: {
      /**
       * Optional. Leave empty to use the project flagged as featured.
       */
      project?: (number | null) | Project;
      badge?: string | null;
      /**
       * e.g. "Mora Coffee / Custom build".
       */
      category?: string | null;
      title?: string | null;
      description?: string | null;
      cta: {
        label: string;
        /**
         * In-page anchor like #work, or a full URL.
         */
        href: string;
      };
      /**
       * e.g. "Read 3 min".
       */
      readTime?: string | null;
      /**
       * Image shown on the stacked card behind the front card.
       */
      backImage?: (number | null) | Media;
      backBadge?: string | null;
    };
  };
  faq?: {
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    heading?: string | null;
    intro?: string | null;
  };
  story?: {
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    title?: string | null;
    intro?: string | null;
    /**
     * Large art word, e.g. "MAKE SPACE".
     */
    artWord?: string | null;
    /**
     * e.g. "Watch our story · 1:30".
     */
    videoLabel?: string | null;
    barLocation?: string | null;
    barNote?: string | null;
  };
  reviews?: {
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    heading?: string | null;
    intro?: string | null;
  };
  services?: {
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    heading?: string | null;
    intro?: string | null;
  };
  contact?: {
    /**
     * Inline HTML is allowed for decorative markup kept from the original design, e.g. <em>…</em>, <br /> or a chip span.
     */
    title?: string | null;
    eyebrow?: string | null;
    heading?: string | null;
    avatars?:
      | {
          initials: string;
          /**
           * Tooltip text, e.g. "Maya — strategy".
           */
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    topics?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    form?: {
      submitLabel?: string | null;
      consent?: string | null;
      successHeading?: string | null;
      successBody?: string | null;
      resetLabel?: string | null;
    };
    infoCard?: {
      emailLabel?: string | null;
      studioLabel?: string | null;
      howWeWorkLabel?: string | null;
      howWeWorkItems?: string[] | null;
    };
  };
  markers: {
    about: {
      number: string;
      label: string;
    };
    work: {
      number: string;
      label: string;
    };
    faq: {
      number: string;
      label: string;
    };
    story: {
      number: string;
      label: string;
    };
    reviews: {
      number: string;
      label: string;
    };
    services: {
      number: string;
      label: string;
    };
    contact: {
      number: string;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Title, SEO defaults, contact details and footer copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  title: string;
  description: string;
  /**
   * Social sharing image. Falls back to /og.svg when empty.
   */
  ogImage?: (number | null) | Media;
  favicon?: string | null;
  themeColor?: string | null;
  contactEmail: string;
  /**
   * Rendered with line breaks preserved.
   */
  address?: string | null;
  footerTagline?: string | null;
  footerBanner?: {
    eyebrow?: string | null;
    heading?: string | null;
    ctaLabel?: string | null;
  };
  copyright?: string | null;
  legalLinks?:
    | {
        label: string;
        /**
         * In-page anchor like #work, or a full URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        /**
         * In-page anchor like #work, or a full URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header menu, header call to action and the footer link columns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerLinks?:
    | {
        label: string;
        /**
         * In-page anchor like #work, or a full URL.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCta: {
    label: string;
    /**
     * In-page anchor like #work, or a full URL.
     */
    href: string;
    id?: string | null;
  };
  footerColumns?:
    | {
        title: string;
        /**
         * Projects and services columns are generated from their collections instead of a manual list.
         */
        source?: ('manual' | 'projects' | 'services') | null;
        links?:
          | {
              label: string;
              /**
               * In-page anchor like #work, or a full URL.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Dismissible bar shown above the header.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement".
 */
export interface Announcement {
  id: number;
  enabled?: boolean | null;
  badge?: string | null;
  message?: string | null;
  link?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        skills?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        locationBadge?: T;
        availability?: T;
        availabilityNote?: T;
        carousel?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        marquee?: T;
      };
  about?:
    | T
    | {
        heading?: T;
        intro?: T;
        tiles?:
          | T
          | {
              label?: T;
              caption?: T;
              variant?: T;
              id?: T;
            };
        pillars?:
          | T
          | {
              label?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  work?:
    | T
    | {
        heading?: T;
        intro?: T;
        filters?:
          | T
          | {
              label?: T;
              key?: T;
              id?: T;
            };
        maxVisible?: T;
        showAllLabel?: T;
        showLessLabel?: T;
        featured?:
          | T
          | {
              project?: T;
              badge?: T;
              category?: T;
              title?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              readTime?: T;
              backImage?: T;
              backBadge?: T;
            };
      };
  faq?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  story?:
    | T
    | {
        title?: T;
        intro?: T;
        artWord?: T;
        videoLabel?: T;
        barLocation?: T;
        barNote?: T;
      };
  reviews?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  services?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        eyebrow?: T;
        heading?: T;
        avatars?:
          | T
          | {
              initials?: T;
              name?: T;
              id?: T;
            };
        topics?:
          | T
          | {
              label?: T;
              id?: T;
            };
        form?:
          | T
          | {
              submitLabel?: T;
              consent?: T;
              successHeading?: T;
              successBody?: T;
              resetLabel?: T;
            };
        infoCard?:
          | T
          | {
              emailLabel?: T;
              studioLabel?: T;
              howWeWorkLabel?: T;
              howWeWorkItems?: T;
            };
      };
  markers?:
    | T
    | {
        about?:
          | T
          | {
              number?: T;
              label?: T;
            };
        work?:
          | T
          | {
              number?: T;
              label?: T;
            };
        faq?:
          | T
          | {
              number?: T;
              label?: T;
            };
        story?:
          | T
          | {
              number?: T;
              label?: T;
            };
        reviews?:
          | T
          | {
              number?: T;
              label?: T;
            };
        services?:
          | T
          | {
              number?: T;
              label?: T;
            };
        contact?:
          | T
          | {
              number?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  ogImage?: T;
  favicon?: T;
  themeColor?: T;
  contactEmail?: T;
  address?: T;
  footerTagline?: T;
  footerBanner?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        ctaLabel?: T;
      };
  copyright?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        source?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement_select".
 */
export interface AnnouncementSelect<T extends boolean = true> {
  enabled?: T;
  badge?: T;
  message?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}